//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldProperties_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTDOCUMENT
    {
        public int CLIENTDOCUMENTID { get; set; }
        public int USERID { get; set; }
        public int CLIENTDOCUMENTTYPEID { get; set; }
        public byte[] CLIENTDOCUMENT1 { get; set; }
        public System.DateTime CLIENTDOCUMENTUPLOADDATE { get; set; }
        public Nullable<System.DateTime> CLIENTDOCUMENTUPLOADEXPIRY { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual CLIENTDOCUMENTTYPE CLIENTDOCUMENTTYPE { get; set; }
    }
}
