//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldProperties_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTDOCUMENTTYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTDOCUMENTTYPE()
        {
            this.CLIENTDOCUMENTs = new HashSet<CLIENTDOCUMENT>();
        }
    
        public int CLIENTDOCUMENTTYPEID { get; set; }
        public string CLIENTDOCUMENTTYPEDESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTDOCUMENT> CLIENTDOCUMENTs { get; set; }
    }
}
