//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldProperties_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANDATE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MANDATE()
        {
            this.PROPERTYMANDATEs = new HashSet<PROPERTYMANDATE>();
        }
    
        public int MANDATEID { get; set; }
        public Nullable<int> MANDATETYPEID { get; set; }
        public System.DateTime MANDATEDATE { get; set; }
        public string MANDATEDOCUMENT { get; set; }
    
        public virtual MANDATETYPE MANDATETYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPERTYMANDATE> PROPERTYMANDATEs { get; set; }
    }
}
