//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldProperties_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTHERBUILDINGDETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OTHERBUILDINGDETAIL()
        {
            this.PROPERTYOTHERBUILDINGDETAILs = new HashSet<PROPERTYOTHERBUILDINGDETAIL>();
        }
    
        public int OTHERBUILDINGDETAILID { get; set; }
        public string OTHERBUILDINGDETAILDESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPERTYOTHERBUILDINGDETAIL> PROPERTYOTHERBUILDINGDETAILs { get; set; }
    }
}
