//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldProperties_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POINTOFINTEREST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POINTOFINTEREST()
        {
            this.SUBURBPOINTOFINTERESTs = new HashSet<SUBURBPOINTOFINTEREST>();
        }
    
        public int POINTOFINTERESTID { get; set; }
        public Nullable<int> POINTOFINTERESTTYPEID { get; set; }
        public string POINTOFINTERESTNAME { get; set; }
    
        public virtual POINTOFINTERESTTYPE POINTOFINTERESTTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBURBPOINTOFINTEREST> SUBURBPOINTOFINTERESTs { get; set; }
    }
}
