//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldProperties_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POTENTIALCLIENT
    {
        public int POTENTIALCLIENTID { get; set; }
        public int USERID { get; set; }
        public string POTENTIALCLIENTNAME { get; set; }
        public string POTENTIALCLIENTSURNAME { get; set; }
        public string POTENTIALCLIENTCONTACTNUMBER { get; set; }
        public string POTENTIALCLIENTEMAIL { get; set; }
        public string POTENTIALCLIENTSUBJECT { get; set; }
        public string POTENTIALCLIENTMESSAGE { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
