//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldProperties_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPERTYDEFECT
    {
        public int PROPERTYDEFECTID { get; set; }
        public Nullable<int> DEFECTID { get; set; }
        public int INSPECTIONID { get; set; }
        public Nullable<int> SPACEID { get; set; }
        public int PROPERTYDEFECTQUANTITY { get; set; }
    
        public virtual DEFECT DEFECT { get; set; }
        public virtual INSPECTION INSPECTION { get; set; }
        public virtual SPACE SPACE { get; set; }
    }
}
