//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldProperties_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPERTYOWNER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROPERTYOWNER()
        {
            this.PROPERTies = new HashSet<PROPERTY>();
        }
    
        public int PROPERTYOWNERID { get; set; }
        public string PROPERTYOWNERNAME { get; set; }
        public string PROPERTYOWNERSURNAME { get; set; }
        public string PROPERTYOWNEREMAIL { get; set; }
        public string PROPERTYOWNERIDNUMBER { get; set; }
        public string PROPERTYOWNERPASSPORTNUMBER { get; set; }
        public string PROPERTYOWNERADDRESS { get; set; }
        public string PROPERTYOWNERCONTACTNUMBER { get; set; }
        public string PROPERTYOWNERALTCONTACTNUMBER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPERTY> PROPERTies { get; set; }
    }
}
