//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldProperties_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPERTY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROPERTY()
        {
            this.ADVERTISEMENTs = new HashSet<ADVERTISEMENT>();
            this.EMPLOYEEPROPERTies = new HashSet<EMPLOYEEPROPERTY>();
            this.INSPECTIONs = new HashSet<INSPECTION>();
            this.LISTINGPICTUREs = new HashSet<LISTINGPICTURE>();
            this.PRICEs = new HashSet<PRICE>();
            this.PROPERTYTERMs = new HashSet<PROPERTYTERM>();
            this.PROPERTYOTHERBUILDINGDETAILs = new HashSet<PROPERTYOTHERBUILDINGDETAIL>();
            this.PROPERTYDOCUMENTs = new HashSet<PROPERTYDOCUMENT>();
            this.PROPERTYMANDATEs = new HashSet<PROPERTYMANDATE>();
            this.PROPERTYSPACEs = new HashSet<PROPERTYSPACE>();
            this.PROPERTYFEATUREs = new HashSet<PROPERTYFEATURE>();
            this.PURCHASEOFFERs = new HashSet<PURCHASEOFFER>();
            this.RENTALs = new HashSet<RENTAL>();
            this.RENTALAPPLICATIONs = new HashSet<RENTALAPPLICATION>();
            this.SALEs = new HashSet<SALE>();
            this.VALUATIONs = new HashSet<VALUATION>();
        }
    
        public int PROPERTYID { get; set; }
        public Nullable<int> SUBURBID { get; set; }
        public Nullable<int> MARKETTYPEID { get; set; }
        public Nullable<int> PROPERTYSTATUSID { get; set; }
        public Nullable<int> PROPERTYOWNERID { get; set; }
        public Nullable<int> PROPERTYTYPEID { get; set; }
        public string PROPERTYADDRESS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADVERTISEMENT> ADVERTISEMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEEPROPERTY> EMPLOYEEPROPERTies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSPECTION> INSPECTIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTINGPICTURE> LISTINGPICTUREs { get; set; }
        public virtual MARKETTYPE MARKETTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRICE> PRICEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPERTYTERM> PROPERTYTERMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPERTYOTHERBUILDINGDETAIL> PROPERTYOTHERBUILDINGDETAILs { get; set; }
        public virtual PROPERTYSTATU PROPERTYSTATU { get; set; }
        public virtual PROPERTYOWNER PROPERTYOWNER { get; set; }
        public virtual PROPERTYTYPE PROPERTYTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPERTYDOCUMENT> PROPERTYDOCUMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPERTYMANDATE> PROPERTYMANDATEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPERTYSPACE> PROPERTYSPACEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPERTYFEATURE> PROPERTYFEATUREs { get; set; }
        public virtual SUBURB SUBURB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASEOFFER> PURCHASEOFFERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTAL> RENTALs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTALAPPLICATION> RENTALAPPLICATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE> SALEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VALUATION> VALUATIONs { get; set; }
    }
}
