//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldProperties_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHASEOFFER
    {
        public int PURCHASEOFFERID { get; set; }
        public int PROPERTYID { get; set; }
        public int PURCHASEOFFERSTATUSID { get; set; }
        public int USERID { get; set; }
        public decimal OFFERAMOUNT { get; set; }
        public System.DateTime OFFERDATE { get; set; }
        public string OFFERDESCRIPTION { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual PROPERTY PROPERTY { get; set; }
        public virtual PURCHASEOFFERSTATU PURCHASEOFFERSTATU { get; set; }
    }
}
