//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldProperties_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENTAL
    {
        public int RENTALID { get; set; }
        public int PROPERTYID { get; set; }
        public Nullable<int> RENTALTYPEID { get; set; }
        public Nullable<int> RENTALSTATUSID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<System.DateTime> RENTALDATESTART { get; set; }
        public Nullable<System.DateTime> RENTALDATEEND { get; set; }
        public string RENTALAGREEMENTDOCUMENT { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual PROPERTY PROPERTY { get; set; }
        public virtual RENTALSTATU RENTALSTATU { get; set; }
        public virtual RENTALTYPE RENTALTYPE { get; set; }
    }
}
