//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldProperties_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPACE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPACE()
        {
            this.PROPERTYDEFECTs = new HashSet<PROPERTYDEFECT>();
            this.PROPERTYSPACEs = new HashSet<PROPERTYSPACE>();
        }
    
        public int SPACEID { get; set; }
        public int SPACETYPEID { get; set; }
        public string SPACEDESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPERTYDEFECT> PROPERTYDEFECTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPERTYSPACE> PROPERTYSPACEs { get; set; }
        public virtual SPACETYPE SPACETYPE { get; set; }
    }
}
