//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldProperties_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBURBPOINTOFINTEREST
    {
        public int SUBURBPOINTOFINTERESTID { get; set; }
        public int POINTOFINTERESTID { get; set; }
        public int SUBURBID { get; set; }
    
        public virtual POINTOFINTEREST POINTOFINTEREST { get; set; }
        public virtual SUBURB SUBURB { get; set; }
    }
}
