//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldProperties_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.POTENTIALCLIENTs = new HashSet<POTENTIALCLIENT>();
        }
    
        public int USERID { get; set; }
        public string USEREMAIL { get; set; }
        public string USERPASSWORD { get; set; }
        public string USERNAME { get; set; }
        public string USERSURNAME { get; set; }
        public string USERCONTACTNUMBER { get; set; }
        public string USERALTCONTACTNUMBER { get; set; }
        public string USERIDNUMBER { get; set; }
        public string USERPASSPORTNUMBER { get; set; }
        public string USERADDRESS { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POTENTIALCLIENT> POTENTIALCLIENTs { get; set; }
    }
}
