//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldProperties_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALUATION
    {
        public int VALUATIONID { get; set; }
        public Nullable<int> IVSTATUSID { get; set; }
        public int PROPERTYID { get; set; }
        public Nullable<int> USERID { get; set; }
        public string VALUATIONDOCUMENT { get; set; }
        public Nullable<System.DateTime> VALUATIONDATE { get; set; }
        public string VALUATIONDESCRIPTION { get; set; }
        public Nullable<decimal> VALUATIONAMOUNT { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual IVSTATU IVSTATU { get; set; }
        public virtual PROPERTY PROPERTY { get; set; }
    }
}
